name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build application
        run: bun run build
        env:
          # Mocked variables for CI
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/reconned?schema=public"
          BETTER_AUTH_SECRET: "mock_secret_for_ci"
          S3_ENDPOINT: "https://mock-s3-endpoint.example.com"
          S3_REGION: "mock-region"
          S3_ACCESS_KEY_ID: "mock_access_key_id"
          S3_SECRET_ACCESS_KEY: "mock_secret_access_key"
          S3_BUCKET_NAME: "mock-bucket"
          GOOGLE_CLIENT_SECRET: "mock_google_client_secret"
          PLAUSIBLE_API_KEY: "mock_plausible_api_key"
          PLAUSIBLE_HOST: "https://mock-plausible.example.com"
          PLAUSIBLE_SITE_ID: "mock-site-id"
          ONESIGNAL_APP_ID: "mock_onesignal_app_id"
          ONESIGNAL_API_KEY: "mock_onesignal_api_key"
          ADMIN_WEBHOOK_TOKEN: "mock_admin_webhook_token"
          
          # Client variables
          NEXT_PUBLIC_CDN_URL: "https://example.com"
          NEXT_PUBLIC_BETTER_AUTH_URL: "https://example.com"
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: "mock_client_id"
          NEXT_PUBLIC_IMGUR_CLIENT_ID: "mock_imgur_client_id"
          NEXT_PUBLIC_CI: "true"
